Class dc.PubSub.Interop.Production Extends Ens.Production
{

Parameter SETTINGS = "ShutdownTimeout,UpdateTimeout,AlertNotificationManager:Alerting,AlertNotificationOperation:Alerting,AlertNotificationRecipients:Alerting,AlertActionWindow:Alerting";

XData ProductionDefinition
{
<Production Name="dc.PubSub.Interop.Production" LogGeneralTraceEvents="false">
  <Description></Description>
  <ActorPoolSize>0</ActorPoolSize>
</Production>
}

}
